### ISSUE TITLE
Brilliant Job!

### ISSUE THREAD

**Issue by zacmilan** [chenchongthu/DeepCoNN#2]
Hi chenchong, after reading your project. I noticed this part 'DeepCoNN++', this part is related to the yelp data set. But after I downloaded yelp's data set, I didn't find the same data set as in ur code like : 
yelp.valid, yelp.test, yelp.train, user_review, item_review

My dataset is downloaded from this link 'https://www.yelp.com/dataset/download' and contains like : 
business.json, photos.json, review.json and etc.. 

Could u tell me where can I find ur dataset? Best Wishes! Thank u :)

**Comment by chenchongthu** [comment]
I've updated a new version of the model, with examples of how to run the codes. I hope it could help you.

**Comment by zacmilan** [comment]
Thank u for ur reply :) 
Like the "examples of how to run the codes" shows, we should do the same processing for the yelp dataset ?
or
The dataset has changed, bacause my downloaded from this link 'https://www.yelp.com/dataset/download' is contains like :
business.json, photos.json, review.json and etc..

Thank u again :+1:

**Comment by chenchongthu** [comment]
Ok,for Yelp dataset, we only use "review.json", and the preprocessing of it is similar as the processing of the example dataset. 

https://github.com/chenchongthu/DeepCoNN/blob/master/pro_data/load_yelp.py

**Comment by zacmilan** [comment]
Thank you for your patience :)
